export type ImportedSearch={title:string;query:string};
export function savedSearchCsv(text:string):ImportedSearch[]{
 if(text.length>524288)throw new Error('El CSV supera 512 KB.');text=text.replace(/^\uFEFF/,'');let rows:string[][]=[],row:string[]=[],cell='',quoted=false,closed=false;
 const pushCell=()=>{row.push(cell);cell='';closed=false;};const pushRow=()=>{pushCell();if(row.some(v=>v.trim()))rows.push(row);row=[];if(rows.length>101)throw new Error('Importa hasta 100 búsquedas por archivo.');};
 for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'){if(text[i+1]==='"'){cell+='"';i++;}else{quoted=false;closed=true;}}else cell+=c;continue;}if(c==='"'){if(cell||closed)throw new Error('Comillas inválidas en el CSV.');quoted=true;}else if(c===',')pushCell();else if(c==='\n'||c==='\r'){if(c==='\r'&&text[i+1]==='\n')i++;pushRow();}else{if(closed&&!/\s/.test(c))throw new Error('Texto inesperado después de comillas.');if(!closed)cell+=c;}}
 if(quoted)throw new Error('El CSV contiene comillas sin cerrar.');if(cell||row.length||closed)pushRow();if(rows.length<2)throw new Error('El CSV no contiene búsquedas.');
 const header=rows.shift()!.map(v=>v.trim().toLowerCase());if(new Set(header).size!==header.length)throw new Error('El CSV repite columnas.');const queryIndex=header.findIndex(v=>['search','query','consulta','busqueda','búsqueda'].includes(v)),nameIndex=header.findIndex(v=>['name','nombre','title','titulo','título'].includes(v));if(queryIndex<0)throw new Error('Falta la columna Search, Query o Consulta.');
 const result=new Map<string,ImportedSearch>();for(const [index,values] of rows.entries()){if(values.length!==header.length)throw new Error('Cantidad de columnas inválida en fila '+(index+2));for(const option of ['case','whole word','path','regex']){const col=header.indexOf(option);if(col>=0&&/^(1|true|yes)$/i.test(values[col].trim()))throw new Error('Fila '+(index+2)+': la opción '+option+' aún requiere equivalencia con el escritorio. No se importó el archivo.');}const query=values[queryIndex].trim(),title=(nameIndex>=0?values[nameIndex]:query.slice(0,200)).trim();if(!query||query.length>4000||title.length>200)throw new Error('Revisa nombre y consulta en fila '+(index+2));if(!result.has(query))result.set(query,{title:title||query.slice(0,200),query});}return [...result.values()];
}
export function mergeImportedSearches(current:any[],imported:ImportedSearch[],id:()=>string,now:string){const next=[...current];for(const entry of imported)if(!next.some(s=>s.query===entry.query))next.push({id:id(),query:entry.query,title:entry.title,updatedAt:now});if(next.length>100)throw new Error('La cuenta superaría 100 búsquedas. Elimina algunas antes de importar.');return next;}
