import {createHash} from 'node:crypto';import {supabaseAdmin} from './supabaseServer';import {normalizePerson,PERSON_ALIASES} from './identityNormalizer';import type {CalendarSettings} from './notionCalendar';
export function notionSourceKey(settings:CalendarSettings){return createHash('sha256').update((settings.notionToken||'')+':'+(process.env.NOTION_CALENDAR_DATA_SOURCE_ID||settings.notionDataSourceId||'')).digest('hex');}
export function snapshotRequestKey(url:URL){const type=url.searchParams.get('type');if(type==='search-index')return 'search-index';if(type==='calendar'&&url.searchParams.get('basic')==='1'&&!url.searchParams.has('enrichOffset')&&!url.searchParams.has('scope')){const date=url.searchParams.get('date');if(/^\d{4}-\d{2}-\d{2}$/.test(date||'')&&Number.isFinite(Date.parse(date!)))return 'calendar:'+date;}return undefined;}
export async function snapshotContext(user:string,settings:CalendarSettings,key:string){const client=supabaseAdmin(),tag=PERSON_ALIASES[normalizePerson(user)]?.[0];const result=await client.from('profiles').select('id').eq('person_tag',tag).eq('active',true).single();if(result.error||!result.data)throw new Error('Perfil de sincronización no disponible.');return {client,userId:result.data.id,source:notionSourceKey(settings),key};}
export type SnapshotContext=Awaited<ReturnType<typeof snapshotContext>>;
export interface SnapshotRow {payload?:any;has_payload:boolean;content_version:string|null;updated_at:string|null;valid:boolean;force_full:boolean;last_error:string|null;lease_until:string|null;retry_after:string|null}
export async function readSnapshot(c:SnapshotContext,metadataOnly=false):Promise<SnapshotRow|null>{const {data,error}=await c.client.from('notion_snapshots').select((metadataOnly?'':'payload,')+'has_payload,content_version,updated_at,valid,force_full,last_error,lease_until,retry_after').eq('user_id',c.userId).eq('source_key',c.source).eq('request_key',c.key).maybeSingle();if(error)throw new Error('No se pudo leer la copia Supabase. Ejecuta la segunda migración.');return data as unknown as SnapshotRow|null;}
export async function claimSnapshot(c:SnapshotContext){const {data,error}=await c.client.rpc('claim_notion_sync',{p_user_id:c.userId,p_source_key:c.source,p_request_key:c.key});if(error)throw new Error('No se pudo iniciar la sincronización Supabase.');return data;}
export async function finishSnapshot(c:SnapshotContext,lease:any,payload:any,errorMessage?:string){const {data,error}=await c.client.rpc('finish_notion_sync',{p_user_id:c.userId,p_source_key:c.source,p_request_key:c.key,p_token:lease.token,p_generation:lease.generation,p_run_id:lease.run_id,p_payload:payload,p_error:errorMessage||null});if(error)throw new Error('No se pudo guardar la copia Supabase.');return data===true;}
export async function invalidateSnapshots(settings:CalendarSettings,forceFull=false){const {error}=await supabaseAdmin().rpc('invalidate_notion_cache',{p_source_key:notionSourceKey(settings),p_force_full:forceFull});if(error)throw new Error('El cambio se guardó en Notion, pero no se pudo invalidar la copia Supabase.');}

export async function readIndexSlice(c:SnapshotContext,offset:number,limit:number,version?:string,knownVersion?:string){const {data,error}=await c.client.rpc("read_notion_index_slice",{p_user_id:c.userId,p_source_key:c.source,p_offset:offset,p_limit:limit,p_version:version||null,p_known_version:knownVersion||null});if(error)throw new Error("No se pudo leer la página del índice. Revisa la segunda migración.");return data;}
