import {supabaseConfigured,supabaseIdentity} from './supabaseServer';
import {createHmac,randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {normalizePerson,PERSON_ALIASES} from './identityNormalizer';
export const SESSION_COOKIE='anfeta_session';
const failures=new Map<string,{count:number;until:number}>();
function configuration(){const secret=process.env.ANFETA_SESSION_SECRET;if(!secret || secret.length<32)throw new Error('Configura ANFETA_SESSION_SECRET y las cuentas del equipo en el servidor.');const users=JSON.parse(process.env.ANFETA_AUTH_USERS || '{}');return {secret,users};}
function credentialFor(user:string,users:Record<string,string>){return Object.entries(users).find(([tag])=>normalizePerson(tag)===normalizePerson(user))?.[1];}
export function hashPassword(password:string,salt=randomBytes(16).toString('hex')){if(password.length<12 || password.length>1024)throw new Error('Usa una contraseña de al menos 12 caracteres.');return 'scrypt:'+salt+':'+scryptSync(password,salt,64).toString('hex');}
function fingerprint(value:string){return createHash('sha256').update(value).digest('hex').slice(0,16);}
export function authenticateUser(user:string,password:string){const {secret,users}=configuration();const person=normalizePerson(user);if(!PERSON_ALIASES[person])throw new Error('Cuenta no válida.');const key=person;const failure=failures.get(key);if(failure && failure.count>=5 && failure.until>Date.now())throw new Error('Demasiados intentos. Espera 15 minutos.');const credential=credentialFor(user,users);let valid=false;
  if(typeof password==='string' && password.length<=1024 && credential){const [kind,salt,hex]=credential.split(':');if(kind==='scrypt' && /^[a-f0-9]{32,}$/i.test(salt || '') && /^[a-f0-9]{128}$/i.test(hex || '')){const actual=scryptSync(password,salt,64);valid=timingSafeEqual(actual,Buffer.from(hex,'hex'));}}
  if(!valid){if(failures.size>128)failures.clear();failures.set(key,{count:failure && failure.until>Date.now()?failure.count+1:1,until:Date.now()+900000});throw new Error('Usuario o contraseña incorrectos.');}failures.delete(key);
  const data=Buffer.from(JSON.stringify({user:person,expires:Date.now()+12*3600000,version:fingerprint(credential!),nonce:randomBytes(16).toString('hex')})).toString('base64url');return {user:person,token:data+'.'+createHmac('sha256',secret).update(data).digest('base64url')};
}
export function sessionActor(request:Request){try{const cookie=request.headers.get('cookie')?.split(';').map(s=>s.trim()).find(s=>s.startsWith(SESSION_COOKIE+'='))?.slice(SESSION_COOKIE.length+1);if(!cookie)return undefined;const {secret,users}=configuration();const [data,signature,extra]=cookie.split('.');if(extra || !data || !signature)return undefined;const expected=createHmac('sha256',secret).update(data).digest();const received=Buffer.from(signature,'base64url');if(received.length!==expected.length || !timingSafeEqual(expected,received))return undefined;const value=JSON.parse(Buffer.from(data,'base64url').toString());const credential=credentialFor(value.user,users);if(value.expires<Date.now() || !credential || fingerprint(credential)!==value.version)return undefined;return normalizePerson(value.user);}catch{return undefined;}}
export async function requireActor(request:Request){if(supabaseConfigured())return (await supabaseIdentity()).person;const actor=sessionActor(request);if(!actor)throw new Error('Inicia sesión para continuar.');return actor;}
export function assertSameOrigin(request:Request){const origin=request.headers.get('origin');if(origin && origin!==new URL(request.url).origin)throw new Error('Origen de solicitud no permitido.');}
