import {supabaseConfigured} from './supabaseServer';import {readSupabasePreferences,updateSupabasePreferences} from './supabasePreferences';
import {notionRequest} from './notionMutations';import {readBlocks,CalendarSettings} from './notionCalendar';import {normalizePerson} from './identityNormalizer';
const PREFIX='[ANFETA_USER_STATE_V1]';const locks=new Set<string>();
export interface UserState {revision:number;values:Record<string,any>;pageId?:string;updatedAt?:string}
async function source(settings:CalendarSettings){const id=process.env.NOTION_APP_STATE_DATA_SOURCE_ID || settings.notionDataSourceId || '2eeabd7d-91b7-8193-a131-000b08cd54e2';const schema=await notionRequest(settings,'data_sources/'+id);const title=Object.entries(schema.properties || {}).find(([,p]:any)=>p.type==='title')?.[0];if(!title)throw new Error('Fuente de preferencias sin título editable.');return {id,title};}
export async function readUserState(settings:CalendarSettings,user:string):Promise<UserState>{if(supabaseConfigured())return readSupabasePreferences(user);return readNotionUserState(settings,user);}
export async function readNotionUserState(settings:CalendarSettings,user:string):Promise<UserState>{const s=await source(settings);const title=PREFIX+' '+normalizePerson(user);const data=await notionRequest(settings,'data_sources/'+s.id+'/query','POST',{page_size:100,filter:{property:s.title,title:{equals:title}},sorts:[{timestamp:'last_edited_time',direction:'descending'}]});if(data.has_more)throw new Error('Hay demasiadas páginas duplicadas de preferencias.');let best:UserState={revision:0,values:{}};
  for(const page of data.results || []){if(page.archived||page.in_trash)continue;for(const block of await readBlocks(settings,page.id)){if(block.type!=='paragraph')continue;const text=(block.paragraph.rich_text || []).map((p:any)=>p.plain_text || p.text?.content || '').join('');if(!text.startsWith(PREFIX))continue;try{const value=JSON.parse(Buffer.from(text.slice(PREFIX.length),'base64').toString());if(value.user===normalizePerson(user)&&Number.isSafeInteger(value.revision)&&value.revision>=best.revision)best={...value,pageId:page.id};}catch{}}}return best;}
export async function updateUserState(settings:CalendarSettings,user:string,patch:Record<string,any>,expectedRevision?:number){if(supabaseConfigured())return updateSupabasePreferences(user,patch,expectedRevision);const key=settings.notionToken+':'+normalizePerson(user);if(locks.has(key))throw new Error('Las preferencias se están guardando. Intenta de nuevo.');locks.add(key);try{const old=await readUserState(settings,user);if(expectedRevision!==undefined && old.revision!==expectedRevision)throw new Error('La configuración cambió en otro dispositivo. Actualiza y vuelve a guardar.');const allowed=['favorites','savedSearches','calendarLayouts','pushSubscriptions','receipts','voiceCommands','notifications','workSessions','pendingTasks'];for(const name of Object.keys(patch))if(!allowed.includes(name))throw new Error('Preferencia no admitida: '+name);const state={user:normalizePerson(user),revision:old.revision+1,values:{...old.values,...patch},updatedAt:new Date().toISOString()};const encoded=PREFIX+Buffer.from(JSON.stringify(state)).toString('base64');if(encoded.length>100000)throw new Error('La configuración excede el tamaño permitido.');const rich_text=(encoded.match(/[\s\S]{1,1900}/g)||[]).map(content=>({type:'text',text:{content}}));
  const child={object:'block',type:'paragraph',paragraph:{rich_text}};let pageId=old.pageId;if(pageId)await notionRequest(settings,'blocks/'+pageId+'/children','PATCH',{children:[child]});else{const s=await source(settings);const page=await notionRequest(settings,'pages','POST',{parent:{data_source_id:s.id},properties:{[s.title]:{title:[{text:{content:PREFIX+' '+normalizePerson(user)}}]}},children:[child]});pageId=page.id;}return {...state,pageId};}finally{locks.delete(key);}}

export async function importNotionPreferences(settings:CalendarSettings,user:string){if(!supabaseConfigured())throw new Error("Configura Supabase antes de importar.");const current=await readSupabasePreferences(user);if(current.revision!==0)throw new Error("Ya hay preferencias en Supabase; no se sobrescribirán.");const old=await readNotionUserState(settings,user);if(!Object.keys(old.values).length)throw new Error("No hay preferencias anteriores de esta cuenta para importar.");return updateSupabasePreferences(user,old.values,0);}
