"use client";
import {filterReminders,reminderOverdue} from '@/lib/reminderFilters';
import React,{useEffect,useState,useCallback,useRef} from 'react';
import {Bell,Plus,Trash2,RefreshCw} from 'lucide-react';
import {anfetaSync} from '@/lib/anfetaBroadcastSync';
import {readApiJson} from '@/lib/readApiJson';
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'America/Mexico_City',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());}
type Item={id:string;title:string;due_date:string;due_time:string;priority:string;completed:boolean;revision:number;creator_id:string;assignee_id:string};
export function RemindersCalendarHost(){const [items,setItems]=useState<Item[]>([]),[people,setPeople]=useState<{id:string;name:string}[]>([]),[current,setCurrent]=useState(''),[date,setDate]=useState(today),[title,setTitle]=useState(''),[time,setTime]=useState('12:00'),[assignee,setAssignee]=useState(''),[priority,setPriority]=useState('medium'),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
const [notice,setNotice]=useState('');
const [scope,setScope]=useState('all');const [now,setNow]=useState(Date.now);useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),30000);return()=>clearInterval(timer);},[]);const visibleItems=filterReminders(items,scope,now);
const requestNumber=useRef(0);
const load=useCallback(async(signal?:AbortSignal)=>{const request=++requestNumber.current;try{const data=await readApiJson(await fetch('/api/reminders?date='+date,{signal,cache:'no-store'}));if(signal?.aborted||request!==requestNumber.current)return;setItems(data.items);setPeople(data.people);setCurrent(data.currentId);setAssignee(old=>old||data.currentId);setError('');}catch(e){if(!signal?.aborted&&request===requestNumber.current)setError(e instanceof Error?e.message:'No se pudieron cargar.');}finally{if(!signal?.aborted&&request===requestNumber.current)setLoading(false);}},[date]);
useEffect(()=>{const controller=new AbortController();setItems([]);setLoading(true);void load(controller.signal);const refresh=()=>{if(!document.hidden)void load(controller.signal);};const timer=setInterval(refresh,30000);window.addEventListener('focus',refresh);document.addEventListener('visibilitychange',refresh);const unsubscribe=anfetaSync.subscribe(message=>{if(message.type==='REMINDERS_CHANGED')refresh();});return()=>{requestNumber.current++;controller.abort();clearInterval(timer);window.removeEventListener('focus',refresh);document.removeEventListener('visibilitychange',refresh);unsubscribe();};},[load]);
async function change(body:any){if(busy)return;setBusy(true);setNotice('');try{const result=await readApiJson(await fetch('/api/reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));if(body.action==='create')setTitle('');if(body.action==='snooze')setNotice('Pospuesto al '+result.item.due_date+' a las '+result.item.due_time.slice(0,5)+'.');await load();anfetaSync.broadcast({type:'REMINDERS_CHANGED'});}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
return <section className="flex-1 flex flex-col min-h-0 bg-[#080B0F] text-slate-200"><header className="flex flex-wrap items-center gap-3 p-3 border-b border-slate-800"><Bell size={18} className="text-cyan-400"/><h2>Recordatorios</h2><select aria-label="Filtrar recordatorios" value={scope} onChange={e=>setScope(e.target.value)} className="rounded bg-slate-900 p-2 text-sm"><option value="all">Todos</option><option value="pending">Pendientes</option><option value="completed">Completados</option><option value="overdue">Vencidos</option></select><input aria-label="Fecha" type="date" value={date} onChange={e=>setDate(e.target.value)} className="bg-slate-900 p-2 rounded"/><span className="text-xs text-slate-400">{items.filter(x=>!x.completed).length} pendientes</span><button aria-label="Actualizar recordatorios" onClick={()=>void load()}><RefreshCw size={16}/></button></header>
{notice&&<p role="status" className="px-3 py-2 text-sm text-cyan-200">{notice}</p>}
{error&&<div role="alert" className="m-3 p-3 rounded border border-red-800 bg-red-950 text-red-100">{error}</div>}
<form onSubmit={e=>{e.preventDefault();void change({action:'create',title,date,time,priority,assigneeId:assignee});}} className="flex flex-wrap gap-2 p-3"><input required maxLength={500} aria-label="Título del recordatorio" placeholder="Nuevo recordatorio" value={title} onChange={e=>setTitle(e.target.value)} className="flex-1 min-w-40 bg-slate-900 rounded p-2"/><input required aria-label="Hora" type="time" value={time} onChange={e=>setTime(e.target.value)} className="bg-slate-900 rounded p-2"/><select aria-label="Persona asignada" value={assignee} onChange={e=>setAssignee(e.target.value)} className="bg-slate-900 rounded p-2">{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select aria-label="Prioridad" value={priority} onChange={e=>setPriority(e.target.value)} className="bg-slate-900 rounded p-2"><option value="low">Baja</option><option value="medium">Normal</option><option value="high">Alta</option><option value="urgent">Urgente</option></select><button disabled={busy||!current} className="flex items-center gap-1 rounded bg-sky-800 px-3 disabled:opacity-40"><Plus size={16}/>{busy?'Guardando…':'Agregar'}</button></form>
<div className="flex-1 overflow-auto p-3 space-y-2">{loading?<p>Cargando recordatorios…</p>:!visibleItems.length?<p className="text-slate-400">No hay recordatorios que coincidan con este día y filtro.</p>:visibleItems.map(item=><article key={item.id} className="flex flex-wrap items-center gap-3 p-3 bg-slate-900/60 border border-slate-800 rounded"><input type="checkbox" aria-label={'Completar '+item.title} checked={item.completed} disabled={busy} onChange={e=>void change({action:'complete',id:item.id,revision:item.revision,completed:e.target.checked})}/><time className="text-cyan-300 text-sm">{item.due_time.slice(0,5)}</time><div className="flex-1 min-w-0"><p className={item.completed?'line-through text-slate-500':'break-words'}>{item.title}{reminderOverdue(item,now)&&<span className="ml-2 rounded bg-rose-950 px-1 text-xs text-rose-200">Vencido</span>}</p><p className="text-xs text-slate-400">{people.find(p=>p.id===item.assignee_id)?.name||'Persona asignada'} · {({low:'Baja',medium:'Normal',high:'Alta',urgent:'Urgente'} as Record<string,string>)[item.priority]}</p></div>{!item.completed&&<select aria-label={'Posponer '+item.title} disabled={busy} value="" onChange={e=>{const minutes=Number(e.target.value);if(minutes)void change({action:'snooze',id:item.id,revision:item.revision,minutes});}} className="rounded border border-slate-700 bg-slate-950 p-1 text-xs"><option value="">Posponer…</option><option value="15">15 minutos</option><option value="60">1 hora</option><option value="1440">24 horas</option></select>}{item.creator_id===current&&<button disabled={busy} aria-label={'Eliminar '+item.title} onClick={()=>void change({action:'delete',id:item.id,revision:item.revision})}><Trash2 size={16} className="text-slate-400"/></button>}</article>)}</div></section>;}
