'use client';
import {useEffect,useRef,useState} from 'react';
import {Video,ChevronDown,Copy,ExternalLink} from 'lucide-react';
// Salas del acceso rápido de SearchView.xaml del escritorio.
const rooms=['eye-rmmg-rgb','omp-srcb-uix','vhv-vyjf-ten'];
export function MeetQuickLinks(){const [open,setOpen]=useState(false),[status,setStatus]=useState('');const container=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
useEffect(()=>{if(!open)return;const outside=(event:PointerEvent)=>{if(!container.current?.contains(event.target as Node))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setOpen(false);trigger.current?.focus()}};document.addEventListener('pointerdown',outside);document.addEventListener('keydown',escape);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('keydown',escape)}},[open]);
async function copy(code:string){try{await navigator.clipboard.writeText('https://meet.google.com/'+code);setStatus('Enlace copiado.')}catch{setStatus('No se pudo copiar. Selecciona el enlace de la sala y cópialo.')}}
return <div ref={container} className="relative shrink-0"><button ref={trigger} type="button" aria-expanded={open} aria-controls="results-meet-links" onClick={()=>{setOpen(!open);setStatus('')}} title="Salas frecuentes de Google Meet" className="flex items-center gap-1 rounded-lg border border-[#2E6288] bg-[#17334C] px-2 py-1 text-[10.5px] font-semibold text-[#A5D9F4] hover:bg-[#20445F] focus-visible:outline-2 focus-visible:outline-cyan-400"><Video size={13}/><span>Meet</span><ChevronDown size={11}/></button>
{open&&<div id="results-meet-links" aria-label="Accesos rápidos a Meet" className="absolute bottom-full right-0 z-[290] mb-2 w-72 max-w-[calc(100vw-24px)] rounded-xl border border-slate-700 bg-[#0F172A] p-2 shadow-xl"><p className="px-2 py-1 text-xs font-semibold text-slate-200">Salas de Meet</p>{rooms.map((code,index)=><div key={code} className="flex items-center gap-1 rounded-lg hover:bg-slate-800"><a href={'https://meet.google.com/'+code} target="_blank" rel="noopener noreferrer" onClick={()=>setOpen(false)} className="flex min-w-0 flex-1 items-center justify-between gap-2 px-2 py-2 text-xs text-cyan-200 focus-visible:outline-2 focus-visible:outline-cyan-400"><span>Meet {index+1} · {code}</span><ExternalLink size={12}/></a><button type="button" title={'Copiar enlace de Meet '+(index+1)} aria-label={'Copiar enlace de Meet '+(index+1)} onClick={()=>copy(code)} className="rounded p-2 text-slate-400 hover:text-cyan-200 focus-visible:outline-2 focus-visible:outline-cyan-400"><Copy size={13}/></button></div>)}<p role="status" className="mt-1 px-2 text-[11px] text-slate-400">{status||'Se abre en una pestaña del navegador actual.'}</p></div>}</div>}
