'use client';
import {useEffect,useRef,useState} from 'react';
import {readApiJson} from '@/lib/readApiJson';
export function NotionBlockTextEditor({pageId,blockId,onClose,onSaved}:{pageId:string;blockId:string;onClose:()=>void;onSaved:(block:any)=>void}){
 const [model,setModel]=useState<any>(null),[texts,setTexts]=useState<string[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const sending=useRef(false),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const controller=new AbortController();dialog.current?.showModal();void fetch('/api/data',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'get-notion-block-editor',payload:{pageId,blockId}})}).then(readApiJson).then(data=>{if(!controller.signal.aborted){setModel(data.block);setTexts(data.block.runs.map((r:any)=>r.text));}}).catch(e=>{if(!controller.signal.aborted)setError(e.message||'No se pudo abrir el bloque.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[pageId,blockId]);
 async function save(){if(sending.current||!model)return;sending.current=true;setSaving(true);setError('');try{const data=await readApiJson(await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'edit-notion-block-text',payload:{pageId,blockId,version:model.version,texts}})}));onSaved(data.block);window.dispatchEvent(new Event('anfeta_data_refreshed'));onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar.');}finally{sending.current=false;setSaving(false);}}
 return <dialog ref={dialog} onCancel={e=>{e.preventDefault();if(!sending.current)onClose();}} className="m-auto w-[min(640px,94vw)] max-h-[85dvh] overflow-auto rounded-xl border border-slate-700 bg-slate-950 p-4 text-slate-200 shadow-xl backdrop:bg-black/70"><form onSubmit={e=>{e.preventDefault();void save();}}><header className="mb-3 flex items-center justify-between"><h2 className="font-semibold">Editar texto del bloque</h2><button type="button" disabled={saving} onClick={onClose} aria-label="Cerrar editor">×</button></header><p className="mb-3 text-xs text-slate-400">Cada fragmento conserva su formato y enlace. Las menciones y ecuaciones son de solo lectura. Guardar texto no marca ni desmarca tareas.</p>{loading&&<p role="status">Cargando bloque…</p>}{error&&<p role="alert" className="mb-3 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-100">{error}</p>}<div className="space-y-3">{model?.runs.map((run:any,index:number)=><label key={index} className="block text-xs">Fragmento {index+1}{run.linked?' · con enlace':''}{run.annotations.code?' · Código':''}{run.annotations.bold?' · negrita':''}{run.annotations.italic?' · cursiva':''}{run.annotations.strikethrough?' · tachado':''}{!run.editable?' · solo lectura':''}<textarea autoFocus={index===0} readOnly={!run.editable} disabled={saving} maxLength={2000} rows={Math.min(8,Math.max(2,texts[index]?.split('\n').length||2))} value={texts[index]||''} onChange={e=>setTexts(old=>old.map((text,i)=>i===index?e.target.value:text))} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2 text-sm read-only:opacity-60"/><span className="text-slate-500">{texts[index]?.length||0}/2000</span></label>)}</div><footer className="mt-4 flex justify-end gap-2"><button type="button" disabled={saving} onClick={onClose} className="rounded border border-slate-700 px-3 py-2">Cancelar</button><button disabled={loading||saving||!model||texts.every((text,i)=>text===model.runs[i].text)} className="rounded bg-sky-800 px-3 py-2 disabled:opacity-40">{saving?'Guardando…':'Guardar texto'}</button></footer></form></dialog>;
}
