'use client';
import {useEffect,useRef,useState} from 'react';
import {readApiJson} from '@/lib/readApiJson';
const types=[['paragraph','Texto'],['heading_1','Encabezado grande'],['heading_2','Encabezado mediano'],['heading_3','Encabezado pequeño'],['bulleted_list_item','Lista con viñeta'],['numbered_list_item','Lista numerada'],['to_do','Tarea pendiente'],['quote','Cita'],['callout','Nota destacada'],['code','Bloque de Código']];
export function NotionNewBlock({pageId,onClose,onSaved}:{pageId:string;onClose:()=>void;onSaved:(block:any)=>void}){
 const dialog=useRef<HTMLDialogElement>(null),sending=useRef(false);const [type,setType]=useState('paragraph'),[text,setText]=useState(''),[annotations,setAnnotations]=useState<Record<string,boolean>>({}),[saving,setSaving]=useState(false),[error,setError]=useState(''),[uncertain,setUncertain]=useState(false);
 useEffect(()=>{dialog.current?.showModal();},[]);
 async function save(){if(sending.current||uncertain||!text.trim())return;sending.current=true;setSaving(true);setError('');try{const response=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'append-notion-block',payload:{pageId,type,text,annotations}})});const data=await readApiJson(response);onSaved(data.block);window.dispatchEvent(new Event('anfeta_data_refreshed'));onClose();}catch(e){const message=e instanceof Error?e.message:'No se confirmó la creación.';setError(message);if(e instanceof TypeError||/no se confirm|antes de volver|Failed to fetch|NetworkError|servidor no pudo/i.test(message))setUncertain(true);}finally{sending.current=false;setSaving(false);}}
 return <dialog ref={dialog} onCancel={e=>{e.preventDefault();if(!sending.current)onClose();}} className="m-auto w-[min(600px,94vw)] max-h-[85dvh] overflow-auto rounded-xl border border-slate-700 bg-slate-950 p-4 text-slate-200 shadow-xl backdrop:bg-black/70"><form onSubmit={e=>{e.preventDefault();void save();}}><h2 className="mb-3 font-semibold">Agregar bloque a Notion</h2><p className="mb-3 text-xs text-slate-400">Se agrega al final de esta página. Las tareas nuevas empiezan sin marcar. Código se cuenta según las reglas de checklist.</p><label className="block text-sm">Tipo<select autoFocus disabled={saving||uncertain} value={type} onChange={e=>setType(e.target.value)} className="mt-1 mb-3 w-full rounded bg-slate-900 p-2">{types.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><fieldset disabled={saving||uncertain} className="mb-3 flex flex-wrap gap-3 text-xs"><legend className="mb-2">Formato de todo el texto</legend>{[['bold','Negrita'],['italic','Cursiva'],['strikethrough','Tachado'],['underline','Subrayado'],['code','Código']].map(([key,label])=><label key={key}><input type="checkbox" checked={!!annotations[key]} onChange={e=>setAnnotations(old=>({...old,[key]:e.target.checked}))}/> {label}</label>)}</fieldset><label className="block text-sm">Contenido<textarea required disabled={saving||uncertain} maxLength={4000} rows={7} value={text} onChange={e=>setText(e.target.value)} className="mt-1 w-full rounded border border-slate-700 bg-slate-900 p-2"/><span className="text-xs text-slate-500">{text.length}/4000</span></label>{error&&<p role="alert" className="mt-3 rounded border border-red-800 bg-red-950 p-3 text-sm text-red-100">{error}</p>}{uncertain&&<p className="mt-2 text-xs text-amber-200">El envío queda detenido para evitar repetirlo. Revisa la página en Notion antes de iniciar otra creación.</p>}<footer className="mt-4 flex justify-end gap-2"><button type="button" disabled={saving} onClick={onClose} className="rounded border border-slate-700 px-3 py-2">{uncertain?'Cerrar':'Cancelar'}</button><button disabled={saving||uncertain||!text.trim()} className="rounded bg-sky-800 px-3 py-2 disabled:opacity-40">{saving?'Agregando…':'Agregar bloque'}</button></footer></form></dialog>;
}
