"use client";
import React,{useEffect,useState} from 'react';
import {GeneralMessages} from './GeneralMessages';
import {calendarTime} from '@/services/calendarPresentation';
function ReviewMessagesHost() {
  const [user,setUser]=useState(''),[items,setItems]=useState<any[]>([]),[selected,setSelected]=useState(''),[entries,setEntries]=useState<any[]>([]),[text,setText]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0);
  useEffect(()=>{const read=()=>{try{setUser(JSON.parse(localStorage.getItem('anfeta_settings') || '{}').currentUser || 'nneft');}catch{setUser('nneft');}};read();window.addEventListener('anfeta_settings_changed',read);return()=>window.removeEventListener('anfeta_settings_changed',read);},[]);
  useEffect(()=>{if(!user)return;const controller=new AbortController();let loading=false;const load=async()=>{if(loading||document.hidden)return;loading=true;try{const res=await fetch('/api/data?type=review-notifications&person='+encodeURIComponent(user),{cache:'no-store',signal:controller.signal});const data=await res.json();if(!res.ok)throw new Error(data.error);setItems(data.items || []);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'No se pudieron cargar los hilos');}finally{loading=false;}};void load();const timer=setInterval(load,30000);return()=>{controller.abort();clearInterval(timer);};},[user]);
  useEffect(()=>{if(!selected)return;const controller=new AbortController();let loading=false;const load=async()=>{if(loading||document.hidden)return;loading=true;try{const res=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({action:'get-review-thread',payload:{pageId:selected,currentUser:user}})});const data=await res.json();if(!res.ok)throw new Error(data.error);setEntries(data.entries || []);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'No se pudo cargar el hilo');}finally{loading=false;}};setEntries([]);setError('');void load();const timer=setInterval(load,30000);return()=>{controller.abort();clearInterval(timer);};},[selected,user,revision]);
  const send=async(e:React.FormEvent)=>{e.preventDefault();if(busy||!text.trim())return;setBusy(true);setError('');try{const res=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'reply-review-thread',payload:{pageId:selected,currentUser:user,text}})});const data=await res.json();if(!res.ok||!data.success)throw new Error(data.error);setText('');setRevision(value=>value+1);}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}};
  return <div className="flex h-full min-w-0 flex-col md:flex-row bg-[#080B0F] text-slate-200"><aside className="w-full md:w-72 shrink-0 max-h-48 md:max-h-none overflow-auto border-r border-slate-800 p-3"><h2 className="text-sm font-semibold mb-3">Hilos de revisión · Notion</h2>{!items.length&&!error&&<p className="text-xs text-slate-400">Sin avisos de revisión para tu cuenta.</p>}{items.map(item=><button key={item.id} onClick={()=>setSelected(item.id)} className={"block w-full text-left text-xs rounded border p-3 mb-2 "+(selected===item.id?'border-cyan-700 bg-slate-800':'border-slate-800')}>{item.title}</button>)}</aside><section className="flex flex-1 min-h-0 min-w-0 flex-col p-4">{error&&<p role="alert" className="rounded border border-rose-800 p-3 text-sm text-rose-300">{error}</p>}{!selected?<p className="text-sm text-slate-400">Selecciona un hilo para consultar su historial y responder.</p>:<><div className="flex-1 overflow-auto space-y-3 py-3">{entries.map((entry,index)=><article key={entry.id || index} className="rounded border border-slate-800 p-3"><p className="text-xs text-cyan-300">{entry.AuthorName} → {entry.RecipientName} · {calendarTime(entry.CreatedAt)}</p><p className="text-sm whitespace-pre-wrap mt-2">{entry.Text}</p></article>)}</div><form onSubmit={send} className="flex gap-2"><input aria-label="Respuesta al hilo" disabled={busy} maxLength={1800} value={text} onChange={e=>setText(e.target.value)} placeholder="Escribe una respuesta…" className="min-w-0 flex-1 rounded bg-slate-800 p-3 text-sm"/><button disabled={busy||!text.trim()} className="rounded bg-cyan-800 px-4 disabled:opacity-40">{busy?'Guardando…':'Responder'}</button></form></>}</section></div>;
}

export function MessagesHost(){const [tab,setTab]=useState<'review'|'general'>(()=>typeof window!=='undefined'&&new URLSearchParams(window.location.search).has('thread')?'general':'review');return <div className="flex flex-col h-full min-h-0"><nav className="flex gap-2 p-2 bg-slate-950 border-b border-slate-800 text-sm text-slate-200">{(['review','general'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={'rounded px-3 py-2 '+(tab===t?'bg-sky-900':'bg-slate-900')}>{t==='review'?'Revisiones':'Conversaciones'}</button>)}</nav><div className="flex-1 min-h-0">{tab==='review'?<ReviewMessagesHost/>:<GeneralMessages/>}</div></div>;}
