import {sharedAccessConfigured,clearSharedGate} from '@/services/sharedAccess';
import {loginSharedAccess,sharedAccessStatus,selectSharedPerson} from '@/services/supabaseServer';
import {NextResponse} from 'next/server';
import {authenticateUser,sessionActor,assertSameOrigin,SESSION_COOKIE} from '@/services/serverAuth';
import {supabaseConfigured,supabaseIdentity,loginSupabase,supabaseSessionClient} from '@/services/supabaseServer';
export const maxDuration=120;
export async function GET(req:Request){if(sharedAccessConfigured()){try{return NextResponse.json({...await sharedAccessStatus(),sharedMode:true},{headers:{'Cache-Control':'no-store'}});}catch(e){return NextResponse.json({authenticated:false,user:'',sharedMode:true,error:e instanceof Error?e.message:'No se pudo verificar el acceso.'},{headers:{'Cache-Control':'no-store'}});}}if(supabaseConfigured()){try{const identity=await supabaseIdentity();return NextResponse.json({authenticated:true,user:identity.person,provider:'supabase'},{headers:{'Cache-Control':'no-store'}});}catch(error){return NextResponse.json({authenticated:false,user:'',provider:'supabase',error:error instanceof Error?error.message:'No se pudo verificar la sesión.'},{headers:{'Cache-Control':'no-store'}});}}const user=sessionActor(req);return NextResponse.json({authenticated:!!user,user:user||'',provider:'legacy'},{headers:{'Cache-Control':'no-store'}});}
export async function POST(req:Request){try{assertSameOrigin(req);const body=await req.json();if(sharedAccessConfigured()){const result=await loginSharedAccess(String(body.password||''));return NextResponse.json({authenticated:true,user:result.person,sharedMode:true,needsPersonSelection:true},{headers:{'Cache-Control':'no-store'}});}if(supabaseConfigured()){const identity=await loginSupabase(String(body.user||''),String(body.password||''));return NextResponse.json({authenticated:true,user:identity.person},{headers:{'Cache-Control':'no-store'}});}const result=authenticateUser(String(body.user||''),String(body.password||''));const response=NextResponse.json({authenticated:true,user:result.user});response.cookies.set(SESSION_COOKIE,result.token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',path:'/',maxAge:43200});return response;}catch(error){return NextResponse.json({error:error instanceof Error?error.message:'No se pudo iniciar sesión.'},{status:401});}}
export async function DELETE(req:Request){try{assertSameOrigin(req);if(sharedAccessConfigured())await clearSharedGate();if(supabaseConfigured()){const client=await supabaseSessionClient();const {error}=await client.auth.signOut();if(error)throw error;}const response=NextResponse.json({success:true});response.cookies.set(SESSION_COOKIE,'',{httpOnly:true,path:'/',maxAge:0});return response;}catch{return NextResponse.json({error:'No se pudo cerrar la sesión.'},{status:400});}}

export async function PATCH(req:Request){try{assertSameOrigin(req);if(!sharedAccessConfigured())return NextResponse.json({error:'El selector requiere acceso compartido.'},{status:400});const body=await req.json();const result=await selectSharedPerson(String(body.person||''));return NextResponse.json({success:true,user:result.person,sharedMode:true},{headers:{'Cache-Control':'no-store'}});}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'No se pudo cambiar persona.'},{status:403});}}
