"use client";
import {useState} from 'react';
import {FinanceStatusBadge} from './FinanceStatusBadge';
import {filterFinance,financeCsv} from '@/lib/financeColumnOptions';
import {financeCardLayout} from '@/lib/financeCardLayout';

export function CalendarFinanceColumn({kind,items,warning,loading=false,width,height,pixelsPerHour,date,order,slot,people,onPosition,onWidth,onRefresh,onClose}: {kind:'cobro'|'pago';items:any[];warning:string;loading?:boolean;width:number;height:number;pixelsPerHour:number;date:string;order:number;slot:number;people:string[];onPosition:(slot:number)=>void;onWidth:(width:number)=>void;onRefresh:()=>void;onClose:()=>void}) {
  const [text,setText]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('time'),[view,setView]=useState('calendar'),[options,setOptions]=useState(false);const visible=filterFinance(items,text,status,sort),statuses=[...new Set(items.map(i=>i.status).filter(Boolean))].sort();
  const laneStyle={backgroundColor:kind==='cobro'?'#21152e':'#102633',borderColor:kind==='cobro'?'#785393':'#316982',borderLeftWidth:3};
  const exportCsv=()=>{const url=URL.createObjectURL(new Blob([financeCsv(visible)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='anfeta-'+kind+'-'+date+'.csv';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  return <div className="min-w-0 border-r border-[#202832] flex flex-col" style={{order,height:height+56,flex:'1 0 '+width+'px',width}}>
    <div className="h-14 shrink-0 bg-[#101722] px-2 relative flex items-center gap-2 text-xs text-cyan-200">
      <strong>{kind==='cobro'?'💰 COBROS':'💳 PAGOS'} · {visible.length}/{items.length}</strong>
      <button disabled={slot===0} onClick={()=>onPosition(slot-1)} title="Mover una posición a la izquierda" aria-label={'Mover '+kind+' a la izquierda'}>‹</button><button disabled={slot===people.length} onClick={()=>onPosition(slot+1)} title="Mover una posición a la derecha" aria-label={'Mover '+kind+' a la derecha'}>›</button><button aria-expanded={options} aria-label={'Opciones de '+kind} onClick={()=>setOptions(!options)} title="Opciones de columna">⋯</button><button onClick={onClose} title="Ocultar columna">×</button>
      {options&&<div className="absolute right-1 top-full z-50 w-64 max-w-[90vw] max-h-[70dvh] overflow-y-auto rounded-lg border border-slate-700 bg-slate-950 p-3 shadow-xl space-y-2 text-slate-200"><div className="flex justify-between"><strong>Opciones · {kind==='cobro'?'Cobros':'Pagos'}</strong><button aria-label="Cerrar opciones" onClick={()=>setOptions(false)}>×</button></div><label className="block">Posición<select aria-label={'Posición de '+kind} className="mt-1 w-full rounded bg-slate-800 p-2" value={slot} onChange={e=>onPosition(Number(e.target.value))}>{people.map((person,index)=><option key={person} value={index}>Antes de {person}</option>)}<option value={people.length}>Al final</option></select></label><label className="block">Buscar<input value={text} onChange={e=>setText(e.target.value)} placeholder="Dominio o concepto…" className="mt-1 w-full rounded bg-slate-800 p-2"/></label><label className="block">Estado<select className="mt-1 w-full rounded bg-slate-800 p-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos</option>{[...new Set([...statuses,...(status?[status]:[])])].map(v=><option key={v}>{v}</option>)}</select></label><label className="block">Orden<select className="mt-1 w-full rounded bg-slate-800 p-2" value={sort} onChange={e=>setSort(e.target.value)}><option value="time">Horario</option><option value="domain">Dominio</option><option value="status">Estado</option></select></label><label className="block">Vista<select className="mt-1 w-full rounded bg-slate-800 p-2" value={view} onChange={e=>setView(e.target.value)}><option value="calendar">Calendario</option><option value="list">Lista completa del día</option></select></label><label className="block">Ancho de todas las columnas<select className="mt-1 w-full rounded bg-slate-800 p-2" value={width} onChange={e=>onWidth(Number(e.target.value))}>{[...new Set([180,260,360,width])].sort((a,b)=>a-b).map(v=><option key={v} value={v}>{v} px</option>)}</select></label><div className="flex flex-wrap gap-2"><button onClick={()=>{setText('');setStatus('');setSort('time');}} className="rounded border border-slate-700 p-2">Limpiar filtros</button><button disabled={loading} onClick={onRefresh} className="rounded border border-slate-700 p-2">Actualizar</button><button disabled={!visible.length||loading} onClick={exportCsv} className="rounded border border-slate-700 p-2">Exportar CSV</button></div><p className="text-[10px] text-slate-400">{statuses.map(v=>v+': '+items.filter(i=>i.status===v).length).join(' · ')||'Sin estados disponibles'}</p></div>}
      {warning && <span title={warning} aria-label={warning}>ⓘ</span>}
    </div>
    <div className="relative flex-1 overflow-y-auto overflow-x-hidden bg-[#080B0F]" style={{height}}>
      {Array.from({length:Math.ceil(height/pixelsPerHour)+1},(_,i)=><div key={i} className="absolute w-full h-px bg-[#161F2B]" style={{top:i*pixelsPerHour}}/>)}
      {warning&&<p role="alert" className="relative z-10 m-2 rounded border border-amber-800 bg-slate-950 p-2 text-xs text-amber-200">{warning}</p>}{loading&&<p role="status" className="relative p-3 text-xs text-cyan-200">Cargando {kind==='cobro'?'cobros':'pagos'}…</p>}{!loading&&!warning&&!visible.length && <p className="relative p-3 text-xs text-slate-500">Sin registros para esta fecha y filtros.</p>}
      {view==='list'?<div className="absolute inset-0 overflow-y-auto pt-1 px-2 pb-3">{warning&&<p className="mb-2 rounded border border-amber-900 bg-slate-950 p-2 text-xs text-amber-200">{warning}</p>}{visible.map(item=><a key={item.id} href={item.url||undefined} target="_blank" rel="noopener noreferrer" title={item.title} style={laneStyle} className="mb-2 block rounded-lg border p-2 text-xs text-slate-200"><p className="text-[10px] text-cyan-300">{new Intl.DateTimeFormat('es-MX',{timeZone:'America/Mexico_City',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(item.start))}</p><FinanceStatusBadge status={item.status}/><strong className="block break-words">{item.domain}</strong><p className="break-words">{item.concept||item.title}</p><p className="mt-1 text-[10px] text-slate-400">{item.person}</p></a>)}</div>:financeCardLayout(visible,date,pixelsPerHour).map(({item,start,top,height:cardHeight})=>{return <a key={item.id} href={item.url || undefined} target="_blank" rel="noopener noreferrer" className="absolute rounded border border-cyan-800/50 bg-[#122128] px-2 py-1 text-xs text-slate-200 overflow-hidden" style={{...laneStyle,top,height:cardHeight,left:3,right:3}} title={item.title}><div className="flex justify-between gap-1 text-[9px]"><strong className="min-w-0 truncate">{kind==='cobro'?'COBRO':'PAGO'} · {String(Math.floor(start/60)).padStart(2,'0')}:{String(start%60).padStart(2,'0')}</strong><FinanceStatusBadge status={item.status}/></div>{item.domain&&<div className="truncate text-[10px] text-cyan-300">{item.domain}</div>}<div className="font-medium line-clamp-2">{item.concept||item.title}</div><div className="text-[9px] text-slate-400 truncate">{item.person}</div></a>;})}
    </div>
  </div>;
}
