"use client";
import React,{useEffect,useState} from 'react';
import {runCalendarAutomation} from '@/services/runCalendarAutomation';
import {calendarTime} from '@/services/calendarPresentation';
export function CalendarAutomationModal({currentUser,date,onClose,onComplete}:{currentUser:string;date:string;onClose:()=>void;onComplete:(report:any)=>void}) {
  const [report,setReport]=useState<any>(),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  useEffect(()=>{const controller=new AbortController();fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},signal:controller.signal,body:JSON.stringify({action:'calendar-automation-preview',payload:{currentUser,date}})}).then(async res=>{const data=await res.json();if(!res.ok)throw new Error(data.error);setReport(data.report);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[currentUser,date]);
  const run=async()=>{setBusy(true);setError('');try{const result=await runCalendarAutomation(currentUser,date,partial=>onComplete(partial));onComplete(result);if(result.failed)setError(result.errors.join(' · '));else onClose();}catch(e){setError(e instanceof Error?e.message:'No se pudo ejecutar');}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-[250] flex items-center justify-center bg-black/70 p-4"><section role="dialog" aria-modal="true" aria-label="Preparar jornada" className="w-full max-w-lg max-h-[85dvh] overflow-auto rounded-xl border border-cyan-800 bg-slate-950 p-5 text-slate-200"><h2 className="font-semibold">Preparar jornada · Robot 05:00</h2><p className="my-2 text-xs text-slate-400">Pendientes y suspendidas de los últimos 14 días. Se conservan sus horarios; revisiones y bloqueos quedan excluidos.</p>{error&&<p role="alert" className="text-rose-300 text-sm">{error}</p>}{!report&&!error&&<p>Cargando propuesta…</p>}{report&&<><p className="text-sm mb-3">{report.movements.length} actividades para mover a hoy.</p><div className="space-y-2">{report.movements.map((move:any)=><div key={move.activityId} className="text-xs border border-slate-800 rounded p-2"><strong>{move.person}</strong> · {move.title}<p className="text-slate-400">{move.originalDate} → {move.targetDate} · {calendarTime(move.start)}–{calendarTime(move.end)}</p></div>)}</div></>}<div className="mt-4 flex justify-end gap-2"><button disabled={busy} onClick={onClose} className="rounded border border-slate-700 px-3 py-2 text-sm">Cancelar</button><button disabled={busy||!report?.movements?.length} onClick={run} className="rounded bg-cyan-700 px-3 py-2 text-sm disabled:opacity-40">{busy?'Guardando en Notion…':'Confirmar movimientos'}</button></div></section></div>;
}
