"use client";
import React,{useMemo,useState} from 'react';
import {NotionCalendarActivity} from '@/types/anfeta';
import {canEditActivity} from '@/services/activityPermissions';
import {planOneClick} from '@/services/calendarPlanner';
import {calendarTime,mexicoDate,mexicoMinutes} from '@/services/calendarPresentation';
export function CalendarBatchModal({activities,currentUser,date,onClose,onSaved}:{activities:NotionCalendarActivity[];currentUser:string;date:string;onClose:()=>void;onSaved:(items:NotionCalendarActivity[])=>void}) {
  const eligible=activities.filter(a=>!a.isReviewMirror&&canEditActivity(currentUser,a));
  const [confirmedIds,setConfirmedIds]=useState<string[]>([]);
  const [selected,setSelected]=useState<string[]>([]),[day,setDay]=useState(date),[person,setPerson]=useState(eligible[0]?.person || ''),[mode,setMode]=useState('date'),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const proposal=useMemo(()=>{
    try {
      if(mode==='plan')return {changes:planOneClick(activities.map(a=>confirmedIds.includes(a.pageId)?{...a,isLocked:true}:a),date,person),error:''};
      return {changes:eligible.filter(a=>selected.includes(a.pageId)).map(a=>{const start=mexicoMinutes(a.start),duration=(Date.parse(a.end)-Date.parse(a.start))/60000;const at=(m:number)=>day+'T'+String(Math.floor(m/60)).padStart(2,'0')+':'+String(m%60).padStart(2,'0')+':00-06:00';return {pageId:a.pageId,title:a.title,start:at(start),end:at(start+duration)};}),error:''};
    }catch(e){return {changes:[],error:e instanceof Error?e.message:'No se pudo preparar'};}
  },[mode,activities,date,person,day,selected,confirmedIds]);
  const save=async()=>{setBusy(true);setError('');try{const res=await fetch('/api/data',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(115000),body:JSON.stringify({action:'calendar-batch-schedule',payload:{currentUser,changes:proposal.changes}})});const data=await res.json();if(!res.ok)throw new Error(data.error);const confirmed=(data.results || []).filter((item:any)=>item.success).map((item:any)=>item.activity);if(confirmed.length){setConfirmedIds(prev=>[...prev,...confirmed.map((a:any)=>a.pageId)]);onSaved(confirmed);}if(data.success)onClose();else{setSelected(prev=>prev.filter(id=>!confirmed.some((a:any)=>a.pageId===id)));setError((data.results || []).filter((item:any)=>!item.success).map((item:any)=>item.error).join(' · '));}}catch(e){setError(e instanceof Error?e.message:'No se pudo guardar');}finally{setBusy(false);}};
  return <div className="fixed inset-0 z-[250] flex items-center justify-center bg-black/70 p-4"><section role="dialog" aria-modal="true" aria-label="Reprogramar actividades" className="max-h-[85dvh] overflow-auto w-full max-w-xl rounded-xl border border-cyan-900 bg-slate-950 p-5 text-slate-200"><h2 className="font-semibold">Reprogramar actividades</h2><div className="flex gap-3 my-3 text-xs"><select value={mode} onChange={e=>setMode(e.target.value)} className="bg-slate-800 p-2 rounded"><option value="date">Mover seleccionadas de fecha</option><option value="plan">Planificar pendientes en un clic</option></select>{mode==='date'?<input aria-label="Fecha de destino" type="date" value={day} onChange={e=>setDay(e.target.value)} className="bg-slate-800 rounded p-2" />:<select aria-label="Persona para planificar" value={person} onChange={e=>setPerson(e.target.value)} className="bg-slate-800 rounded p-2">{[...new Set(eligible.map(a=>a.person))].map(p=><option key={p}>{p}</option>)}</select>}</div><p className="text-xs text-slate-400 mb-3">La propuesta se guarda únicamente al confirmar. Se respetan bloqueos, permisos y actividades ya programadas.</p>
    {mode==='date'&&<div className="max-h-48 overflow-auto space-y-2">{eligible.map(a=><label key={a.pageId} className="flex items-center gap-2 text-xs"><input type="checkbox" checked={selected.includes(a.pageId)} onChange={e=>setSelected(prev=>e.target.checked?[...prev,a.pageId]:prev.filter(id=>id!==a.pageId))} />{a.person} · {a.title}</label>)}</div>}
    <div className="mt-3 space-y-2">{proposal.changes.map(a=><p key={a.pageId} className="rounded border border-slate-800 p-2 text-xs">{a.title}<br/><span className="text-cyan-300">{mexicoDate(a.start)} · {calendarTime(a.start)}–{calendarTime(a.end)}</span></p>)}</div>{(error||proposal.error)&&<p role="alert" className="text-rose-300 text-sm mt-2">{error||proposal.error}</p>}<div className="flex gap-2 justify-end mt-4"><button disabled={busy} onClick={onClose} className="rounded border border-slate-700 p-2">Cancelar</button><button disabled={busy||!proposal.changes.length||proposal.changes.length>30} onClick={save} className="rounded bg-cyan-800 p-2 disabled:opacity-40">{busy?'Guardando…':'Confirmar '+proposal.changes.length+' movimientos'}</button></div></section></div>;
}
