import {NextResponse,after} from 'next/server';
import {requireActor,assertSameOrigin} from '@/services/serverAuth';
import {supabaseConfigured,supabaseIdentity,supabaseAdmin} from '@/services/supabaseServer';
import {normalizePerson} from '@/services/identityNormalizer';
import {sendPwaPush} from '@/services/pwaPush';import {getSettings} from '@/services/serverSettings';
async function account(req:Request){await requireActor(req);if(!supabaseConfigured())throw new Error('Configura Supabase y ejecuta la quinta migración para conversaciones generales.');return supabaseIdentity();}
function failure(e:unknown){const message=e instanceof Error?e.message:'No se pudo completar la conversación.';return NextResponse.json({error:message},{status:/Inicia sesión/.test(message)?401:502});}
export async function GET(req:Request){try{const identity=await account(req),url=new URL(req.url),thread=url.searchParams.get('thread');const profiles=await supabaseAdmin().from('profiles').select('id,person_tag').eq('active',true);if(profiles.error)throw new Error('No se pudieron leer las personas.');const people=profiles.data.map(p=>({id:p.id,name:normalizePerson(p.person_tag)}));if(thread){const conversation=await identity.client.from('conversations').select('*').eq('id',thread).single();if(conversation.error) return NextResponse.json({error:'Conversación no disponible.'},{status:404});let query=identity.client.from('conversation_messages').select('*').eq('conversation_id',thread).order('id',{ascending:false}).limit(100);const before=url.searchParams.get('before');if(before){if(!/^\d+$/.test(before))return NextResponse.json({error:'Cursor inválido.'},{status:400});query=query.lt('id',before);}const messages=await query;if(messages.error)throw new Error('No se pudieron leer los mensajes.');return NextResponse.json({conversation:conversation.data,items:messages.data.reverse(),people,currentId:identity.id,hasMore:messages.data.length===100},{headers:{'Cache-Control':'no-store'}});}const [threads,states]=await Promise.all([identity.client.from('conversations').select('*').order('updated_at',{ascending:false}).limit(200),identity.client.from('conversation_states').select('*')]);if(threads.error||states.error)throw new Error('No se pudieron leer los hilos. Ejecuta la quinta migración.');return NextResponse.json({items:threads.data.map(t=>{const state=states.data.find(s=>s.conversation_id===t.id);return {...t,status:state?.status||'open',unread:t.last_message_id>(state?.last_read_id||0)};}),people,currentId:identity.id},{headers:{'Cache-Control':'no-store'}});}catch(e){return failure(e);}}
export async function POST(req:Request){try{assertSameOrigin(req);const identity=await account(req),body=await req.json();if(!['create','send','read','status'].includes(body.action))return NextResponse.json({error:'Acción inválida.'},{status:400});const input=body.input||{};if(['create','send'].includes(body.action)&&(typeof input.text!=='string'||!input.text.trim()||input.text.length>4000))return NextResponse.json({error:'Escribe entre 1 y 4000 caracteres.'},{status:400});if(body.action==='create'&&(typeof input.title!=='string'||!input.title.trim()||input.title.length>200||!Array.isArray(input.members)||input.members.length>19))return NextResponse.json({error:'Revisa asunto y participantes.'},{status:400});const admin=supabaseAdmin(),result=await admin.rpc('change_conversation',{p_actor:identity.id,p_action:body.action,p_input:input});if(result.error)throw new Error('No se pudo guardar. Revisa participantes, permisos y migración.');if(['create','send'].includes(body.action)){const sender=identity.id,thread=result.data.thread;after(async()=>{try{const conversation=await admin.from('conversations').select('members,title').eq('id',thread).single();const profiles=await admin.from('profiles').select('id,person_tag').eq('active',true).in('id',(conversation.data?.members||[]).filter((id:string)=>id!==sender));for(const p of profiles.data||[])await sendPwaPush(getSettings(),normalizePerson(p.person_tag),{title:'Mensaje ANFETA',body:conversation.data?.title||'Nueva conversación',tag:'conversation-'+thread,url:'/?view=messages&thread='+thread});}catch{console.warn('El mensaje se guardó; no se confirmó el aviso PWA.');}});}return NextResponse.json({success:true,...result.data});}catch(e){return failure(e);}}
