"use client";
import {useState} from 'react';
import {PERSON_ALIASES,PERSON_METADATA} from '@/services/identityNormalizer';
import {readApiJson} from '@/lib/readApiJson';
export function PersonSelector({currentUser,onClose}:{currentUser?:string;onClose?:()=>void}){
 const [person,setPerson]=useState(currentUser||'Neftali'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function choose(e:React.FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{await readApiJson(await fetch('/api/auth',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({person})}));localStorage.setItem('anfeta_person_changed',String(Date.now()));window.location.reload();}catch(e){setError(e instanceof Error?e.message:'No se pudo elegir la persona.');setBusy(false);}}
 return <div className="fixed inset-0 z-[300] grid place-items-center bg-black/85 backdrop-blur p-4"><form onSubmit={choose} className="w-full max-w-sm rounded-2xl border border-cyan-900 bg-[#0F172A] p-6 space-y-4 text-slate-100"><h2 className="text-lg font-semibold text-cyan-300">¿Quién está usando ANFETA?</h2><p className="text-sm text-slate-400">Elige tu persona para trabajar con sus actividades y permisos.</p>{error&&<p role="alert" className="rounded border border-red-900 bg-red-950 p-3 text-sm">{error}</p>}<label className="block text-sm">Persona<select aria-label="Persona activa" disabled={busy} value={person} onChange={e=>setPerson(e.target.value)} className="mt-2 block w-full rounded border border-slate-700 bg-slate-950 p-3">{Object.keys(PERSON_ALIASES).map(name=><option key={name} value={name}>{name} · {['John','Isaias','Genaro'].includes(name)?'Revisor':PERSON_METADATA[name]?.role||'Equipo'}</option>)}</select></label><p className="text-xs text-slate-400">Todos pueden enviar sus actividades a revisión. John, Isaías y Genaro pueden revisarlas.</p><div className="flex gap-2">{onClose&&<button type="button" disabled={busy} onClick={onClose} className="rounded border border-slate-700 px-4 py-2">Cancelar</button>}<button disabled={busy} className="flex-1 rounded bg-sky-700 px-4 py-2 font-semibold">{busy?'Activando persona…':'Continuar'}</button></div></form></div>;
}
